name: scraper

on:
  push:
    branches: [ master ]
  schedule:
  - cron: "0 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        git config --local user.email "scraper@covidsafe.watch"

        git config --local user.name "Scraper Bot"
        
        git remote add upstream "https://github.com/AU-COVIDSafe/mobile-ios.git"

        git fetch upstream master

        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"

        git fetch github master

        git checkout -B master github/master

        git reset upstream/master --hard

        git reset github/master --soft

        git add .

        COMMITTED="NO"

        git commit -a -m "New code" && COMMITTED="YES" || exit 0

        git push github master

        if [ $COMMITTED == "YES" ]; then

          TIMESTAMP=`date +"%s"`

          git checkout -B $TIMESTAMP upstream/master

          git push github $TIMESTAMP

        fi
